# site settings
title: Tanya Motwani
subtitle: 
email: motwani.tanya220@gmail.com
description: An aspiring ML engineer
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://tanya-motwani.github.io/" # the base hostname & protocol for your site
author:
street_address: Indraprastha Towers
city: Ahmedabad
state: Gujarat
zip_code: 380052
country: India
phone: +91-9978978234

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://github.com/Tanya-Motwani/
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed

theme: jekyll-theme-midnight
